### ISSUE TITLE
erro ao baixar o arquivo js.abr

### ISSUE THREAD

**Issue by fraurino** [wppconnect-team/WPP4Delphi#12]
realizar os ajustes abaixo para download automático.

👉🏾 uTWPPConnect.Classes.pas

✔️ constructor TUrlIndy.Create;
```
de: SSLOptions.SSLVersions := [sslvTLSv1_1];
para: SLOptions.SSLVersions :=[sslvTLSv1, sslvTLSv1_1, sslvTLSv1_2];
```

✔️ function TUrlIndy.GetUrl(const Purl: String): Boolean;
```
de: DownLoadInternetFile(TInjectJS_JSUrlPadrao, 'js.abr');
para: Get(Purl, FReturnUrl);  
```

**Comment by marcelo386** [comment]
Acabei de Subir o Ajuste na Unit uTWPPConnect.Classes.pas
