### ISSUE TITLE
Erro de abertura do projeto (mudanca de maquina dev para client)

### ISSUE THREAD

**Issue by fraurino** [wppconnect-team/WPP4Delphi#13]
causa provável: configuração do path no arquivo ConfTWPPConnect.ini

error:  **Exception Exception in module WPPConnectDemo.exe at 0058AF44.**

solução manual: **deletar o arquivo ConfTWPPConnect.ini;**

solução direto no componente:

👉🏾 **uTWPPConnect.ConfigCEF;**

✔️**function TCEFConfig.TestaOk(POldValue, PNewValue: String):Boolean;**

```
if not DirectoryExists(LDir) then
**de:** raise Exception.Create(Format(MSG_ExceptPath, [LDir]));
**para:**  deletefile(pwidechar(ExtractFilePath(Application.ExeName) + NomeArquivoIni)) ;
```

**Comment by marcelo386** [comment]
Ajustado pode fazer update dos fontes, obrigado pela contribuição
