### ISSUE TITLE
Memory leak após receber ligação (chamada)

### ISSUE THREAD

**Issue by paulohaguiar** [wppconnect-team/WPP4Delphi#19]
após receber uma ligação sempre que método GetIncomingiCall é chamado e passado para TIncomingiCall.Create é possível simular o memory leak ao fechar projeto. 

componente está funcionando corretamente, porém acredito que algum objeto JSON não está sendo destruído, se você colocar o projeto para **ReportMemoryLeaksOnShutDown=True** consegue simular o vazamento de memória ao receber uma ligação.

Tem aquela função de KillTask no Form Close do demo, seria interessante testar com ela comentada.

tentei no Create TIncomingiCall dar um freeAndNil no objeto JSON porém ainda não tive sucesso. 

`
![MEMORY LEAK](https://user-images.githubusercontent.com/109989212/180863962-d8dceab0-83b8-467b-8fa3-48d16f442345.png)
`

**Comment by marcelo386** [comment]
não encontrei o vazamento de memória citado
