### ISSUE TITLE
D10.2.3 error

### ISSUE THREAD

**Issue by limelect** [wppconnect-team/WPP4Delphi#2]
On D10.2.3 file u_principal; line 317
vConv.UpdateDataSet(JObj)
I changed to vConv.UpdateDataSet.

Furthermore, when I connect I get a blank page.
I went back to inject.exe and it does not connect either.
Blank page. It use to connect.
Whatsapp made many changes to its web applications.

**Comment by marcelo386** [comment]
I uploaded the fix, not to Bug in Delphi 10.2.3, you can update the sources and test.

**Comment by limelect** [comment]
Compiled the new source.
It compiles.
BUT connect msg on white screen and then white screen.

**Comment by marcelo386** [comment]
compile a 64bit version, this error happens, because of ram overflow, the 64bit version allocates more memory.
The Device you are testing, do not leave conversations unread even if archived, this ends up consuming a lot of TChromium memory
