### ISSUE TITLE
problem with sending positions on whatsapp

### ISSUE THREAD

**Issue by eugeniocel** [wppconnect-team/WPP4Delphi#23]
Hello, I have a problem with sending positions on whatsapp, if as options I set the buttons the position is not sent for example lat: 40.7752164, lng: 14.5921692, name: "EC Eugenio Celentano", address: "VIA G. MATTEOTTI , 42 SAN MARZANO SUL SARNO 84010 SA ", useTemplateButtons: true, createChat: true, title:" EC Eugenio Celentano ", footer:" VIA G. MATTEOTTI, 42 SAN MARZANO SUL SARNO 84010 SA ", buttons: [{phoneNumber:" 000 0000000 ", text:" Call Phone "}] can someone help me? until a few weeks ago it worked quietly 
thanks

**Comment by marcelo386** [comment]
I opened an issue in WAJS, to fix this option, it hasn't been fixed yet

**Comment by eugeniocel** [comment]
Thanks
