### ISSUE TITLE
Evento para pegar o ID do Whats ao enviar Localização

### ISSUE THREAD

**Issue by andreysisplan** [wppconnect-team/WPP4Delphi#25]
Desenvolver o evento OnGet_sendLocationMessageEx para recuperar o ID do whats após o envio de uma localização

**Comment by marcelo386** [comment]
frDemo.TWPPConnect1.SendLocationMessageEx(ed_num.text, options, '123');
Evento: TWPPConnect1Get_SendLocationMessageEx

https://www.loom.com/share/637c858fb28b4fa8ba7012c4e9d004e1
