### ISSUE TITLE
exception on start demo

### ISSUE THREAD

**Issue by Marijsoft** [wppconnect-team/WPP4Delphi#26]
when i try to run demo i have this error 01/01/1500 is not valid a datetime (exception econvert error)

**Comment by marcelo386** [comment]
Could you give more details where this error occurred, which function you were using.
Test with the latest version.

**Comment by Marijsoft** [comment]
[](url)
![error](https://user-images.githubusercontent.com/4884515/192039455-d9855eb2-8b6a-4bab-b694-03e68a9f4192.png)

i download, clean and reinstall all but i have the same problem when i try  the start demo, all files is in the directory
