### ISSUE TITLE
Implementação dos Eventos isMainLoaded e isMainReady

### ISSUE THREAD

**Issue by zLuckr0x** [wppconnect-team/WPP4Delphi#27]
Implementação de 2 recursos novos ja disponiveis no js.

**isMainLoaded** é quando está conectado, mas ainda carregando as Mensagens.
**isMainReady** é quando está pronto para uso.

**Comment by marcelo386** [comment]
https://loom.com/share/94c5cce78766443dbd3142148da71cb4

Eventos:
  TWPPConnect1GetIsLoaded e TWPPConnect1GetIsReady
