### ISSUE TITLE
Error Installation

### ISSUE THREAD

**Issue by nanaksr** [wppconnect-team/WPP4Delphi#28]
I have Error on installation package "WPP4Delphi\Packages\TWPP4DelphiCollection.dpk"

`Checking project dependencies...
Building TWPP4DelphiCollection.dproj (Debug, Win32)
brcc32 command line for "TWPP4DelphiCollection.vrc"
  c:\program files (x86)\embarcadero\studio\21.0\bin\cgrc.exe -c65001 TWPP4DelphiCollection.vrc -foTWPP4DelphiCollection.res 
brcc32 command line for "TWPP4DelphiCollectionResource.rc"
  c:\program files (x86)\embarcadero\studio\21.0\bin\cgrc.exe -c65001 TWPP4DelphiCollectionResource.rc -foTWPP4DelphiCollection.dres 
dcc32 command line for "TWPP4DelphiCollection.dpk"
  c:\program files (x86)\embarcadero\studio\21.0\bin\dcc32.exe -$O- -$W+ --no-config -B -Q -Z -TX.bpl 
  -AGenerics.Collections=System.Generics.Collections;Generics.Defaults=System.Generics.Defaults;WinTypes=Winapi.Windows;WinProcs=Winapi.Windows;
  DbiTypes=BDE;DbiProcs=BDE;DbiErrs=BDE -DDEBUG -I"C:\Program Files (x86)\Winsoft\ComPort\Delphi104";F:\DELPHI\_component\ComPort\Delphi104;"c:\program 
  files (x86)\embarcadero\studio\21.0\lib\Win32\release";C:\Users\nanak\Documents\Embarcadero\Studio\21.0\Imports;"c:\program files 
  (x86)\embarcadero\studio\21.0\Imports";C:\Users\Public\Documents\Embarcadero\Studio\21.0\Dcp;"c:\program files (x86)\embarcadero\studio\21.0\include";
  "F:\DELPHI\_component\zylgsm1.48\Delphi 10.4 Sydney\Win32";F:\DELPHI\_component\IPW9;"C:\Program Files (x86)\CrystalNet Technologies\.Net Runtime 
  Library for Delphi\Source";F:\DELPHI\_component\TRAWPrinter-master;"C:\Program Files (x86)\CrystalNet Technologies\dotNetCore4Delphi\Source";
  "C:\Program Files (x86)\CrystalNet Technologies\dotNetCore4Delphi\Dcu\Delphi27\Win32\Release";"C:\Program Files (x86)\CrystalNet 
  Technologies\dotNetCore4Delphi\Source\runtimes\win-x86";F:\DELPHI\_component\DIHtmlParser8.2.0\D10_4\win32;
  F:\DELPHI\_component\DIHtmlParser8.2.0\Source;F:\DELPHI\_component\CEF4Delphi-101.0.4951.67\source;F:\DELPHI\_component\WPP4Delphi-main\Source;
  F:\DELPHI\_component\WPP4Delphi-main\Source\Model;F:\DELPHI\_component\WPP4Delphi-main\Source\Services;
  F:\DELPHI\_component\WPP4Delphi-main\Source\View;F:\DELPHI\_component\WPP4Delphi-main\Packages\Compilados 
  -LEC:\Users\Public\Documents\Embarcadero\Studio\21.0\Bpl -LNC:\Users\Public\Documents\Embarcadero\Studio\21.0\Dcp -NSSystem.Win;Data.Win;Datasnap.Win;
  Web.Win;Soap.Win;Xml.Win;Bde;System;Xml;Data;Datasnap;Web;Soap;Winapi;Vcl.Samples;Vcl;Vcl.Imaging;Vcl.Touch;Vcl.Shell; -O"C:\Program Files 
  (x86)\Winsoft\ComPort\Delphi104";F:\DELPHI\_component\ComPort\Delphi104;"c:\program files (x86)\embarcadero\studio\21.0\lib\Win32\release";
  C:\Users\nanak\Documents\Embarcadero\Studio\21.0\Imports;"c:\program files (x86)\embarcadero\studio\21.0\Imports";
  C:\Users\Public\Documents\Embarcadero\Studio\21.0\Dcp;"c:\program files (x86)\embarcadero\studio\21.0\include";
  "F:\DELPHI\_component\zylgsm1.48\Delphi 10.4 Sydney\Win32";F:\DELPHI\_component\IPW9;"C:\Program Files (x86)\CrystalNet Technologies\.Net Runtime 
  Library for Delphi\Source";F:\DELPHI\_component\TRAWPrinter-master;"C:\Program Files (x86)\CrystalNet Technologies\dotNetCore4Delphi\Source";
  "C:\Program Files (x86)\CrystalNet Technologies\dotNetCore4Delphi\Dcu\Delphi27\Win32\Release";"C:\Program Files (x86)\CrystalNet 
  Technologies\dotNetCore4Delphi\Source\runtimes\win-x86";F:\DELPHI\_component\DIHtmlParser8.2.0\D10_4\win32;
  F:\DELPHI\_component\DIHtmlParser8.2.0\Source;F:\DELPHI\_component\CEF4Delphi-101.0.4951.67\source;F:\DELPHI\_component\WPP4Delphi-main\Source;
  F:\DELPHI\_component\WPP4Delphi-main\Source\Model;F:\DELPHI\_component\WPP4Delphi-main\Source\Services;
  F:\DELPHI\_component\WPP4Delphi-main\Source\View;F:\DELPHI\_component\WPP4Delphi-main\Packages\Compilados -R"C:\Program Files 
  (x86)\Winsoft\ComPort\Delphi104";F:\DELPHI\_component\ComPort\Delphi104;"c:\program files (x86)\embarcadero\studio\21.0\lib\Win32\release";
  C:\Users\nanak\Documents\Embarcadero\Studio\21.0\Imports;"c:\program files (x86)\embarcadero\studio\21.0\Imports";
  C:\Users\Public\Documents\Embarcadero\Studio\21.0\Dcp;"c:\program files (x86)\embarcadero\studio\21.0\include";
  "F:\DELPHI\_component\zylgsm1.48\Delphi 10.4 Sydney\Win32";F:\DELPHI\_component\IPW9;"C:\Program Files (x86)\CrystalNet Technologies\.Net Runtime 
  Library for Delphi\Source";F:\DELPHI\_component\TRAWPrinter-master;"C:\Program Files (x86)\CrystalNet Technologies\dotNetCore4Delphi\Source";
  "C:\Program Files (x86)\CrystalNet Technologies\dotNetCore4Delphi\Dcu\Delphi27\Win32\Release";"C:\Program Files (x86)\CrystalNet 
  Technologies\dotNetCore4Delphi\Source\runtimes\win-x86";F:\DELPHI\_component\DIHtmlParser8.2.0\D10_4\win32;
  F:\DELPHI\_component\DIHtmlParser8.2.0\Source;F:\DELPHI\_component\CEF4Delphi-101.0.4951.67\source;F:\DELPHI\_component\WPP4Delphi-main\Source;
  F:\DELPHI\_component\WPP4Delphi-main\Source\Model;F:\DELPHI\_component\WPP4Delphi-main\Source\Services;
  F:\DELPHI\_component\WPP4Delphi-main\Source\View;F:\DELPHI\_component\WPP4Delphi-main\Packages\Compilados -U"C:\Program Files 
  (x86)\Winsoft\ComPort\Delphi104";F:\DELPHI\_component\ComPort\Delphi104;"c:\program files (x86)\embarcadero\studio\21.0\lib\Win32\release";
  C:\Users\nanak\Documents\Embarcadero\Studio\21.0\Imports;"c:\program files (x86)\embarcadero\studio\21.0\Imports";
  C:\Users\Public\Documents\Embarcadero\Studio\21.0\Dcp;"c:\program files (x86)\embarcadero\studio\21.0\include";
  "F:\DELPHI\_component\zylgsm1.48\Delphi 10.4 Sydney\Win32";F:\DELPHI\_component\IPW9;"C:\Program Files (x86)\CrystalNet Technologies\.Net Runtime 
  Library for Delphi\Source";F:\DELPHI\_component\TRAWPrinter-master;"C:\Program Files (x86)\CrystalNet Technologies\dotNetCore4Delphi\Source";
  "C:\Program Files (x86)\CrystalNet Technologies\dotNetCore4Delphi\Dcu\Delphi27\Win32\Release";"C:\Program Files (x86)\CrystalNet 
  Technologies\dotNetCore4Delphi\Source\runtimes\win-x86";F:\DELPHI\_component\DIHtmlParser8.2.0\D10_4\win32;
  F:\DELPHI\_component\DIHtmlParser8.2.0\Source;F:\DELPHI\_component\CEF4Delphi-101.0.4951.67\source;F:\DELPHI\_component\WPP4Delphi-main\Source;
  F:\DELPHI\_component\WPP4Delphi-main\Source\Model;F:\DELPHI\_component\WPP4Delphi-main\Source\Services;
  F:\DELPHI\_component\WPP4Delphi-main\Source\View;F:\DELPHI\_component\WPP4Delphi-main\Packages\Compilados -K00400000 --description:WPP4Delphi -GD 
  -NBC:\Users\Public\Documents\Embarcadero\Studio\21.0\Dcp -NHC:\Users\Public\Documents\Embarcadero\Studio\21.0\hpp\Win32  TWPP4DelphiCollection.dpk   
[dcc32 Warning] uTWPPConnect.Diversos.pas(73): W1000 Symbol 'Format' is deprecated: 'Use TJSONAncestor.Format instead'
[dcc32 Warning] uTWPPConnect.Diversos.pas(73): W1000 Symbol 'Format' is deprecated: 'Use TJSONAncestor.Format instead'
[dcc32 Warning] uTWPPConnect.Classes.pas(1322): W1010 Method 'Destroy' hides virtual method of base type 'TClassPadrao'
[dcc32 Warning] uTWPPConnect.Classes.pas(1330): W1010 Method 'Destroy' hides virtual method of base type 'TClassPadrao'
[dcc32 Warning] uTWPPConnect.Classes.pas(1338): W1010 Method 'Destroy' hides virtual method of base type 'TClassPadrao'
[dcc32 Warning] uTWPPConnect.Classes.pas(1358): W1010 Method 'Destroy' hides virtual method of base type 'TClassPadrao'
[dcc32 Hint] uTWPPConnect.ConfigCEF.pas(301): H2077 Value assigned to 'TCEFConfig.VersaoCEF4Aceita' never used
[dcc32 Hint] uTWPPConnect.pas(875): H2164 Variable 'lThread' is declared but never used in 'TWPPConnect.DeleteChat'
[dcc32 Hint] uTWPPConnect.pas(900): H2164 Variable 'lThread' is declared but never used in 'TWPPConnect.deleteConversation'
[dcc32 Error] uTWPPConnect.pas(1175): E2035 Not enough actual parameters
[dcc32 Error] uTWPPConnect.pas(1221): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(1255): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(1300): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(1332): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(1366): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(1398): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(1430): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(1462): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(1494): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(1528): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(1562): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(1711): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(1743): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(1829): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(1865): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(1907): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(1944): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(1986): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(2431): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(2478): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(2548): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(2593): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(2743): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(2772): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(2864): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(2912): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(2959): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(3006): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(3054): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(3102): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(3143): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(3190): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(3219): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(3261): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(3308): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(3355): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(3384): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(3413): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(3456): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(3504): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(3548): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] uTWPPConnect.pas(3685): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Warning] uTWPPConnect.pas(3940): W1044 Suspicious typecast of string to PAnsiChar
[dcc32 Warning] uTWPPConnect.pas(3943): W1044 Suspicious typecast of string to PAnsiChar
[dcc32 Error] uTWPPConnect.pas(3987): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Fatal Error] uTWPPConnect.ConfigCEF.pas(54): F2063 Could not compile used unit 'uTWPPConnect.pas'
Failed
Elapsed time: 00:00:00.9
uTWPPConnect.pas(1): Line endings are LF, but RAD Studio requires CRLF. Consider converting or check your source control settings.`

**Comment by marcelo386** [comment]
update the fonts and perform the installation again

**Comment by nanaksr** [comment]
Ok done
