### ISSUE TITLE
Adição de ações de identificação e reação ao envio com falha...

### ISSUE THREAD

**Issue by ThiagoPedro** [wppconnect-team/WPP4Delphi#33]
1. Identificar falha de envio;
Há ocorrência no whatsapp de falhas de envios.
Identificar essas ocorrências.
![Falha_no_Envio](https://user-images.githubusercontent.com/5951550/200271435-d034c6d7-ea24-4b4b-87f9-9b96cd05ce10.png)

2. Ter a opção de "Tentar novamente" para as mensagens com falhas de envios;

**Comment by marcelo386** [comment]
basta monitorar o ack da mensagem, para saber se foi entregue tem que ser maior que 0
