### ISSUE TITLE
problema ao detectar a reconexão do twppconect no delphi

### ISSUE THREAD

**Issue by ghiberlm** [wppconnect-team/WPP4Delphi#36]
a demonstração nunca tenta se reconectar.
na minha opinião é:
 estou percebendo que existe uma variável chamada whatsapps que está em 0 para entrar no evento VerifyWhatsApp existe uma condição que verifica se whatsapps = 0 então está offline então está prestes a chamar TWPPConnect1.Check(NumberExists '17981388414'); exceto fim;
É disparado o evento TWPPConnect1CheckNumberExists não qual whatsappsms:=1 até está tudo bem, o problema é que estando na internet ele ou não o evento sempre será disparado portanto a condição nunca é atendida se whatsappsms = 0 Então
TWPPConnect1.RebootWPP e não permite reiniciar, agradeço se puder me ajudar estou usando as fontes mais recentes e tentando testar ou demo quando a internet cai e tento reconectar forçado.

**Comment by marcelo386** [comment]
a ideia deste processo e testar se está funcionando a injeção do javascript
