### ISSUE TITLE
Problem to sendmessagex with buttons in options

### ISSUE THREAD

**Issue by fabriciohausman** [wppconnect-team/WPP4Delphi#49]
After last Whatsapp update the devices stoped receive messages with buttons. The messages is send but the contect not receive.
Any suggestion?

**Comment by daviladanielc** [comment]
É um bug do whatsapp web, a equipe está verificando.

**Comment by fabriciohausman** [comment]
Obrigado!

**Comment by vagnerfabiog** [comment]
@fabriciohausman baixei a versão hoje dos componentes, fiz o teste pelo Demo e estou com o mesmo problema que voce citou, voce conseguiu resolver o problema ?
