### ISSUE TITLE
Problemas envio de áudio

### ISSUE THREAD

**Issue by DjotaHasse** [wppconnect-team/WPP4Delphi#51]
Ao tentar enviar áudio com a função SenFileMessageEx, o console retorna um warning e não envia o áudio.
![WhatsApp Image 2023-03-24 at 14 15 29](https://user-images.githubusercontent.com/54808117/227612130-7f3c3174-acd8-44b6-a4ac-ca5068cbadc0.jpeg)

**Comment by marcelo386** [comment]
Feito o teste não encontrei o problema citado, testei com audio mp3 e ogg

**Comment by edgardmessias** [comment]
@marcelo386 , isso é um problema relacionado ao autoplay do chrome, na qual está tentando usar o áudio para conversão, mas não houve nenhuma interação na página.

Para alterar o comportamento, pode se usar a flag: `--autoplay-policy=no-user-gesture-required`

Leia mais aqui: https://developer.chrome.com/blog/autoplay/
