### ISSUE TITLE
Problem to sendmessagex with buttons in options

### ISSUE THREAD

**Issue by vagnerfabiog** [wppconnect-team/WPP4Delphi#54]

**Comment by vagnerfabiog** [comment]
After last Whatsapp update the devices stoped receive messages with buttons. The messages is send but the contect not receive.
Any suggestion?

**Comment by vagnerfabiog** [comment]
Fiz a atualização da ultima versão, mas mesmo assim o envio de botão não funciona, alguem tem alguma ideia.

**Comment by marcelo386** [comment]
https://www.youtube.com/live/Ihvhhu8UZZo?feature=share

Assista o Podcast com Edgard, foi explicado como está o uso dos botões

**Comment by wos83** [comment]
> https://www.youtube.com/live/Ihvhhu8UZZo?feature=share
> 
> Assista o Podcast com Edgard, foi explicado como está o uso dos botões

Pra quem facilitar escute apartir de 25:00 minutos.
