### ISSUE TITLE
Lista/Menu Button Error

### ISSUE THREAD

**Issue by Karimmagdy111** [wppconnect-team/WPP4Delphi#55]
In WPPConnectDemo when I click Lista/Menu button it send menu list in Chromium but in actual Whatsapp it doesn't send

**Comment by marcelo386** [comment]
no lib is working this option Meta has blocked the use of this functionality, only the Official API will be able to send buttons and list

no longer exists, the META blocked it directly on the server, the flaw that allowed the upload has been corrected by the Facebook team

use numerical option or keywords

Choose an option from the menu below
1 - Option 1
2 - Option 2
3 - Option 3
4 - Option 4
