### ISSUE TITLE
abrir watzap

### ISSUE THREAD

**Issue by lucianocirola** [wppconnect-team/WPP4Delphi#57]
esta abrindo o zap ?
no meu não gera qrcode

**Comment by marcelo386** [comment]
Revise a sua instalação do CEF, apague os diretórios antigos. Confirme o library path não está apontando para pasta antigas

Limpa a pasta cache

Verifique se o arquivo "js.abr" está na última versão

**Comment by lucianocirola** [comment]
blza
consegui agora
valeuu amigo

Em qui., 22 de jun. de 2023 às 10:38, MARCELO DOS SANTOS DE OLIVEIRA <
***@***.***> escreveu:
