### ISSUE TITLE
send buttons not work can you check it ?

### ISSUE THREAD

**Issue by elmagekmosaad** [wppconnect-team/WPP4Delphi#61]

**Comment by marcelo386** [comment]
no lib is working this option Meta has blocked the use of this functionality, only the Official API will be able to send buttons and list

no longer exists, the META blocked it directly on the server, the flaw that allowed the upload has been corrected by the Facebook team

use numerical option or keywords

Choose an option from the menu below
1 - Option 1
2 - Option 2
3 - Option 3
4 - Option 4
