### ISSUE TITLE
Há um problema com a seguinte função sendImage

### ISSUE THREAD

**Issue by hazem-it** [wppconnect-team/WPP4Delphi#62]
![Capture](https://github.com/wppconnect-team/WPP4Delphi/assets/115902713/ad8179da-0f91-443b-8218-ea4e8d745e85)

**Comment by marcelo386** [comment]
deprecated function, use frDemo.TWPPConnect1.SendFileMessageEx(ed_num.text, caminhoArquivo, '123', caption, isFigurinha);

![WhatsApp Image 2023-09-25 at 15 21 42](https://github.com/wppconnect-team/WPP4Delphi/assets/69150213/9b6c9a9c-fcb8-4876-bd87-c4bae7c735e5)

**Comment by marcelo386** [comment]
ou para Base64

frDemo.TWPPConnect1.SendFileMessageEx(ed_num.text, LBase64.Text, options, '123');

tem o Exemplo na versão Demo de ambas as formas
