### ISSUE TITLE
default country code

### ISSUE THREAD

**Issue by irwanto82** [wppconnect-team/WPP4Delphi#64]
in unit uTWPPConnect.AdjustNumber;
line 141

it should not permanent string 55, should be from variable etc, maybe can be setting from .ini file
in my country 62

`    if Length(LClearNum) <=  (LengthDDI + LengthDDD + LengthPhone + 1 + LInc) Then //14 then
    begin
      if (Length(LClearNum) <= (LengthDDD + LengthPhone + LInc)) or (Length(PNum) <= (LengthDDD + LengthPhone + LInc)) then
      begin
        if (Copy(LClearNum, 0, LengthDDI) <> DDIDefault.ToString)
        or ((Copy(PNum,1,2) = '55') and (Length(PNum) = 10)) //(55)8125-3929 Ajust com DDD 55
        or ((Copy(PNum,1,2) = '55') and (Length(PNum) = 11)) //(55)98125-3929 Ajust com DDD 55
        then
          LClearNum := DDIDefault.ToString + LClearNum;
        Result := LClearNum +  CardContact;
      end;
    end;`

**Comment by marcelo386** [comment]
Fixed DDI Default
