### ISSUE TITLE
Whatsapp Bussiness 2.3

### ISSUE THREAD

**Issue by danielsantb** [wppconnect-team/WPP4Delphi#69]
Alguem ja testou no Business 2.3?

Queria migrar para esse projeto pq o TInject parou , mas nao tenho certeza que aqui ja foi resolvido este problema.

**Comment by marcelo386** [comment]
Foi resolvido sim, entra no nosso grupo 
https://chat.whatsapp.com/HzLflMQVjOPK9bpjzlxcMO
