### ISSUE TITLE
Erro no pedido getAllChats , getAllGroups

### ISSUE THREAD

**Issue by hazem-it** [wppconnect-team/WPP4Delphi#70]
Ocorre um erro e pode demorar muito para responder e receber dados

-----------------------------------

WAPI.getAllGroups()
Promise { <state>: "pending" }
​
<state>: "pending"
​
<prototype>: Promise.prototype { … }
​​
catch: function catch()
​​​
length: 1
​​​
name: "catch"
​​​
<prototype>: function ()
​​
constructor: function Promise()
​​
finally: function finally()
​​
then: function then()
​​
Symbol(Symbol.toStringTag): "Promise"
​​
<prototype>: Object { … }
​​​
__defineGetter__: function __defineGetter__()
​​​
__defineSetter__: function __defineSetter__()
​​​
__lookupGetter__: function __lookupGetter__()
​​​
__lookupSetter__: function __lookupSetter__()
​​​
__proto__: 
​​​
constructor: function Object()
​​​
hasOwnProperty: function hasOwnProperty()
​​​
isPrototypeOf: function isPrototypeOf()
​​​
propertyIsEnumerable: function propertyIsEnumerable()
​​​
toLocaleString: function toLocaleString()
​​​
toString: function toString()
​​​
valueOf: function valueOf()
​​​
<get __proto__()>: function __proto__()
​​​
<set __proto__()>: function __proto__()

**Comment by marcelo386** [comment]
Testou com a versão atual?
