### ISSUE TITLE
Há um erro na função CheckNumberExists

### ISSUE THREAD

**Issue by hazem-it** [wppconnect-team/WPP4Delphi#73]
![Capture](https://github.com/wppconnect-team/WPP4Delphi/assets/115902713/5f7732cd-cfd8-45bc-9c76-feab78d07a1f)
Essa mensagem aparece e depois demora muito, até 15 minutos, e aí aparece o resultado

**Comment by marcelo386** [comment]
pela mensagem deu um estouro no console log, necessário limpar ou dar um reload na página injetar novamente o js.abr

comando para dar um reload é TWPPConnect1.RebootWPP;

ou console.clear(); para limpar o historico do console.log atual

**Comment by marcelo386** [comment]
FrmConsole.Console_Clear;  para limpar

**Comment by hazem-it** [comment]
![Capture](https://github.com/wppconnect-team/WPP4Delphi/assets/115902713/b768eb1d-c267-406e-8f8b-554bf0c61f4a)
Limpei o histórico e a mesma mensagem se repetiu e demorou muito para buscar os dados

**Comment by hazem-it** [comment]
> ![Capture](https://private-user-images.githubusercontent.com/115902713/318173570-b768eb1d-c267-406e-8f8b-554bf0c61f4a.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3ODAyNDAsIm5iZiI6MTcxMTc3OTk0MCwicGF0aCI6Ii8xMTU5MDI3MTMvMzE4MTczNTcwLWI3NjhlYjFkLWMyNjctNDA2ZS04ZjhiLTU1NGJmMGM2MWY0YS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMFQwNjI1NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05M2Q2OGRjNjlhZjEyOWFmNmM3MzVjMTJiYzJlYzY5ZTkxMTM3YjBjMzc5MjdhODMzNjJjYjJmNTBiMDJhZTQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HJ48pSKqvew8L-AMyx5bK8LxDFy8yZMpzh7E1yZ1F5A) Limpei o histórico e a mesma mensagem se repetiu e demorou muito para buscar os dados

Isso só acontece na primeira vez depois de escanear o código e fazer login pela primeira vez

**Comment by marcelo386** [comment]
Foi feito alguns ajustes no WA-JS, verifica se resolveu o problema
