### ISSUE TITLE
Unable create ConfTWPPConnect.ini

### ISSUE THREAD

**Issue by enricogaggero** [wppconnect-team/WPP4Delphi#76]
When I try to put TWPPConnect component on a form I have "Unable to write C:\Program Files (x86)\Embarcadero\Studio\23.0\bin\ConfTWPPConnect.ini" and I cant'use the component.
If I open a form with TWPPConnect component I have same error and the component disapperar.

**Comment by ThiagoPedro** [comment]
Run as administrator
