### ISSUE TITLE
uTWPPConnect.Console Chromium1.OnConsoleMessage has incompatible parameter list

### ISSUE THREAD

**Issue by enricogaggero** [wppconnect-team/WPP4Delphi#77]
![Cattura](https://github.com/wppconnect-team/WPP4Delphi/assets/24946314/0e26ee91-fc94-4721-b4e5-a8566ed4f9a7)

**Comment by marcelo386** [comment]
what is the version of your delphi and CEF4Delphi?

**Comment by enricogaggero** [comment]
Embarcadero® Delphi 12 Version 29.0.50491.5718 

uCEFVersion.inc 
  CEF_SUPPORTED_VERSION_MAJOR   = 122;
  CEF_SUPPORTED_VERSION_MINOR   = 1;
  CEF_SUPPORTED_VERSION_RELEASE = 13;
  CEF_SUPPORTED_VERSION_BUILD   = 0;

  CEF_CHROMEELF_VERSION_MAJOR   = CEF_SUPPORTED_VERSION_MAJOR;
  CEF_CHROMEELF_VERSION_MINOR   = 0;
  CEF_CHROMEELF_VERSION_RELEASE = 6261;
  CEF_CHROMEELF_VERSION_BUILD   = 130;
