### ISSUE TITLE
erro delphi CE 10.3

### ISSUE THREAD

**Issue by fraurino** [wppconnect-team/WPP4Delphi#8]
erro ao instalar componente
[dcc32 Fatal Error] uTWPPConnect.Classes.pas(40): F1026 File not found: 'TWPPConnectDiretiva.inc'
para resolver, tive que comentar a linha

unit uTWPPConnect.Classes;
interface
---> //{$I TWPPConnectDiretiva.inc}

mas ao instalar ocorre o erro abaixo

---------------------------
Error
---------------------------
Cannot load package 'TInjectCollection.'  It contains unit 'UCSV.Import', which is also contained in package 'TWPP4DelphiCollection'.
---------------------------
OK   
---------------------------

como resolver?

**Comment by fraurino** [comment]
**resolvido**
conseguir removendo o component tInject do Delphi

[Window Title]
Information

[Content]
Package C:\Users\Public\Documents\Embarcadero\Studio\20.0\Bpl\TWPP4DelphiCollection.bpl has been installed.
The following new component(s) have been registered: TWPPConnect.

[OK]

**Comment by marcelo386** [comment]
Valeu por reportar
