### ISSUE TITLE
Undeclared identifier: 'WOD_NEW_FOREGROUND_TAB'

### ISSUE THREAD

**Issue by Magayver89** [wppconnect-team/WPP4Delphi#81]
![image](https://github.com/wppconnect-team/WPP4Delphi/assets/143232642/6a872edd-ac91-41fb-ac7e-139f3355cbae)

![image](https://github.com/wppconnect-team/WPP4Delphi/assets/143232642/bf782326-ce3e-4335-806f-146d849c053d)

**Comment by marcelo386** [comment]
É só ler o comentário e criar a Diretiva de Compilação, conforme indicado

Just read the comment and create the Compilation Directive, as indicated

**Comment by rzzanatta** [comment]
Desculpe a ignorância, mas sou novo no Delphi.
O erro comigo é o mesmo, mas não entendi mesmo que diretiva coloco e onde;
Você poderia postar aqui como ficaria por favor?

**Comment by marcelo386** [comment]
....\WPP4Delphi\Packages\Compilados\V2...\TWPPConnectDiretiva.inc

Tirar o ponto da linha
.CEFCurrentVersion

Alterar o .inc antes de Abrir o .DPK da instalação

**Comment by rzzanatta** [comment]
Cara, muito obrigado. 
Deu certo.
Só tive que editar o TWPP4DelphiCollection.dpk e adicionar isso no IndyIPClient,  IndyIPCommon no requires e deu tudo certo.
Vai que alguém também precise disso.
Até :)
