### ISSUE TITLE
Multiple Sessions

### ISSUE THREAD

**Issue by kayaliabd** [wppconnect-team/WPP4Delphi#82]
in the description you said WPPConnect is Multiple Sessions support!
dose it means I can use multi WhatsApp account on multi sessions ?
if so, how I can I use this feature ?

Thank you!

**Comment by marcelo386** [comment]
By creating a folder with the application and cache folder on your WhatsApp account, each connected number will have its own directory

You can also use our projects such as Server, which is more practical for managing multiple sessions
