### ISSUE TITLE
sendListMenu not work

### ISSUE THREAD

**Issue by Hima00007** [wppconnect-team/WPP4Delphi#84]
// Send List menu
const list = [
    {
      title: "Pasta",
      rows: [
        {
          title: "Ravioli Lasagna",
          description: "Made with layers of frozen cheese",
        }
      ]
    },
    {
      title: "Dessert",
      rows: [
        {
          title: "Baked Ricotta Cake",
          description: "Sweets pecan baklava rolls",
        },
        {
          title: "Lemon Meringue Pie",
          description: "Pastry filled with lemonand meringue.",
        }
      ]
    }
  ];

await WAPI.sendListMenu('000000000000@c.us', 'Title', 'subTitle', 'Description', 'menu', list)
  .then((result) => {
    console.log('Result: ', result); //return object success
  })
  .catch((erro) => {
    console.error('Error when sending: ', erro); //return object error
  });

**Comment by marcelo386** [comment]
https://wppconnect.io/wa-js/functions/chat.sendListMessage.html

consult the documentation, you are passing the wrong values ​​from the List assembly

**Comment by Hima00007** [comment]
thanks this is work

> https://wppconnect.io/wa-js/functions/chat.sendListMessage.html
> 
> consult the documentation, you are passing the wrong values ​​from the List assembly
