### ISSUE TITLE
sendButtons not work

### ISSUE THREAD

**Issue by Hima00007** [wppconnect-team/WPP4Delphi#85]
// Send Messages with Buttons Reply
const buttons = [
  {
    "buttonText": {
      "displayText": "Text of Button 1"
      }
    },
  {
    "buttonText": {
      "displayText": "Text of Button 2"
      }
    }
  ]
await WAPI.sendButtons('000000000000@c.us', 'Title', 'Description', buttons)
  .then((result) => {
    console.log('Result: ', result); //return object success
  })
  .catch((erro) => {
    console.error('Error when sending: ', erro); //return object error
  });

**Comment by marcelo386** [comment]
sendbuttons deprecated
