### ISSUE TITLE
File not found: 'TWPPConnectDiretiva.inc'

### ISSUE THREAD

**Issue by mbnoimi** [wppconnect-team/WPP4Delphi#89]
Hi,

Whenever I build my tiny test I get (I use recent commit 4834cb8b922959ac839a960cdc47b509c3e14a6b):

```
[dcc32 Fatal Error] uTWPPConnect.pas(35): F1026 File not found: 'TWPPConnectDiretiva.inc'
```

What's wrong?

I added a the needed source paths into my project as mentioned below:
![image](https://github.com/user-attachments/assets/31de1b19-a7d3-4835-bc08-20ba7c7f86fa)

![image](https://github.com/user-attachments/assets/d0826378-ba5f-49a9-abd9-1557920fbf10)

Code my example:

```pas
unit MaintForm;

interface

uses
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes,
  Vcl.Graphics, Vcl.Controls, Vcl.Forms, Vcl.Dialogs, Vcl.StdCtrls, Vcl.ExtCtrls,
  uTWPPConnect;

type
  TForm1 = class(TForm)
    btnSendMessage: TButton;
    edtPhoneNumber: TEdit;
    memoMessage: TMemo;
    lblStatus: TLabel;
    imgQrCode: TImage;
    procedure btnSendMessageClick(Sender: TObject);
    procedure FormCreate(Sender: TObject);
  private
    { Private declarations }
    WPP: uTWPPConnect.TWPPConnect;
    procedure UpdateStatus(Status: string);
  public
    { Public declarations }
  end;

var
  Form1: TForm1;

implementation

{$R *.dfm}

procedure TForm1.FormCreate(Sender: TObject);
begin
  WPP := uTWPPConnect.TWPPConnect.Create(Self);
  WPP.OnGetQrCode := procedure(Sender: TObject; const QrCodeImage: TBitmap)
    begin
      imgQrCode.Picture.Assign(QrCodeImage);
    end;
  UpdateStatus('Not Connected');
end;

procedure TForm1.UpdateStatus(Status: string);
begin
  lblStatus.Caption := 'Status: ' + Status;
end;

procedure TForm1.btnSendMessageClick(Sender: TObject);
var
  TargetNumber, MessageText: string;
begin
  TargetNumber := edtPhoneNumber.Text + '@c.us';
  MessageText := memoMessage.Lines.Text;

  if WPP.Auth(True) then
  begin
    UpdateStatus('Connected');
    WPP.Send(TargetNumber, MessageText);
  end
  else
  begin
    UpdateStatus('Authentication required. Please scan the QR code.');
    ShowMessage('Authentication failed. Please scan the QR code.');
  end;
end;

end.
```

**Comment by mbnoimi** [comment]
Sorry for the silly question but I couldn't understand installation steps mentioned in README.md (Google translate didn't help me much)

**Comment by marcelo386** [comment]
Folder path

WPP4Delphi\Packages\Compilados
WPP4Delphi\Source\Other

Inside the Packages\Compilados folder, there are subfolders D23, D24, D25, D26, D27 and D28, add the correct folder to the library path according to your version of Delphi See at: https://delphidabbler.com/notes/version-numbers or http://docwiki.embarcadero.com/RADStudio/Sydney/en/Compiler_Versions

**Comment by mbnoimi** [comment]
> Inside the Packages\Compilados folder, there are subfolders D23, D24, D25, D26, D27 and D28,

Thank you,
Did that but I got another error!

```
[dcc32 Error] uTWPPConnect.Console.pas(460): E2003 Undeclared identifier: 'WOD_NEW_FOREGROUND_TAB'
[dcc32 Error] uTWPPConnect.Console.pas(461): E2003 Undeclared identifier: 'WOD_NEW_BACKGROUND_TAB'
[dcc32 Error] uTWPPConnect.Console.pas(462): E2003 Undeclared identifier: 'WOD_NEW_POPUP'
[dcc32 Error] uTWPPConnect.Console.pas(463): E2003 Undeclared identifier: 'WOD_NEW_WINDOW'
[dcc32 Fatal Error] uTWPPConnect.pas(486): F2063 Could not compile used unit 'uTWPPConnect.languages.pas'
Failed
```

![image](https://github.com/user-attachments/assets/f5e5f5aa-abe4-4f10-a866-eefdf124bf83)

**Comment by mbnoimi** [comment]
BTW, The content of `.\Packages\Compilados\VD27`, `.\Packages\Compilados\VD28` and `.\Packages\Compilados\VD29` is identical (f24da3c54815837aa26ca463e7ce1ff83862dd53)!

**Comment by marcelo386** [comment]
Add compilation directive in your delphi CEFCurrentVersion

**Comment by mbnoimi** [comment]
> Add compilation directive in your delphi CEFCurrentVersion

Thanks it works.
