### ISSUE TITLE
Dependency project

### ISSUE THREAD

**Issue by mbnoimi** [wppconnect-team/WPP4Delphi#90]
Hi,

Does WPP4Delphi works standalone without the need to install [wa-js](https://github.com/wppconnect-team/wa-js) with it?

**Comment by marcelo386** [comment]
Wajs is inside the js.abr script file which has some additional customizations for use in Delphi using CEF4DELPHI which has the built-in browser, thus being able to inject the script into the browser console and obtain the WhatsAppWeb functionalities

**Comment by mbnoimi** [comment]
thx
