### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by mbnoimi** [wppconnect-team/WPP4Delphi#92]
Hi,

I struggled with WPP4Delphi installation so I tried to use it directly from the source code instead of the installation https://github.com/wppconnect-team/WPP4Delphi/issues/91#issuecomment-2286284251 but I reached to a dead end so I pulled the recent WPP4Delphi source code and gave installation process another try but I failed again.

May you please help me?

I did all the steps mentioned in README until I reached to:

```
- Abra o arquivo "...WPP4Delphi\Packages\TWPP4DelphiCollection.dpk"
- Então faça um Build (shift+F9) e então "Install" (botão direito do mouse no Project Manager)
``` 

but I get this error message:

```
[dcc32 Error] uTWPPConnect.Console.pas(491): E2003 Undeclared identifier: 'WOD_NEW_FOREGROUND_TAB'
[dcc32 Error] uTWPPConnect.Console.pas(492): E2003 Undeclared identifier: 'WOD_NEW_BACKGROUND_TAB'
[dcc32 Error] uTWPPConnect.Console.pas(493): E2003 Undeclared identifier: 'WOD_NEW_POPUP'
[dcc32 Error] uTWPPConnect.Console.pas(494): E2003 Undeclared identifier: 'WOD_NEW_WINDOW'
[dcc32 Fatal Error] uTWPPConnect.pas(486): F2063 Could not compile used unit 'uTWPPConnect.languages.pas'
Failed
```

Some notes:
- **CEF4Delphi** installed successfully.
- All the paths are absolutely correct!
![image](https://github.com/user-attachments/assets/973a4f21-d85e-40f1-bea3-d867336d0433)
- Tried to add **CEF4Delphi** sources path into **TWPP4DelphiCollection.bpl** but didn't fix the issue
![image](https://github.com/user-attachments/assets/06d44f6f-ce76-4a7c-85db-74e66d5e785e)
- Tried to add `CEFCurrentVersion` into **TWPP4DelphiCollection.bpl** project setting but didn't fix the issue
![image](https://github.com/user-attachments/assets/40742a23-fcde-4df4-8f45-f7729362eb8c)

**Comment by mbnoimi** [comment]
This is unsolved issue. Why you closed it?!
@marcelo386

**Comment by marcelo386** [comment]
This issue has been resolved, the installation instructions are in the readme, the broken links have been fixed, and an additional step has been added for CEF versions higher than 120.

**Comment by mbnoimi** [comment]
> and an additional step has been added for CEF versions higher than 120.

Thanks. I could finally install WPP4Delphi successfully.
