### ISSUE TITLE
Translation in Italian Language

### ISSUE THREAD

**Issue by enricogaggero** [wppconnect-team/WPP4Delphi#94]
If you planned to insert Italian translation of messages here is my contribute:
procedure TTranslatorInject.LanguageItalian;
begin
  SetResourceString(@MSG_ConfigCEF_ExceptNotFoundPATH     , 'Non è possibile eseguire questa operazione dopo che il componente è stato inizializzato');
  SetResourceString(@MSG_ConfigCEF_ExceptConnection       , 'Errore di connessione con il componente');
  SetResourceString(@MSG_ConfigCEF_ExceptBrowse           , 'Errore nella creazione del browser in CEF');
  SetResourceString(@MSG_ConfigCEF_ExceptConnetServ       , 'Non sei connesso al server di servizio');
  SetResourceString(@MSG_ConfigCEF_ExceptConsoleNaoPronto , 'La console non ha ancora ottenuto i comandi per INJECT JS');
  SetResourceString(@MSG_ConfigCEF_ExceptVersaoErrada     , 'La tua versione di CEF4 non è compatibile, aggiorna la tua libreria su https://github.com/salvadordf/CEF4Delphi' + slinebreak + 'Versione richiesta: %s' + slinebreak + 'Versione identificata: %s');
  SetResourceString(@MSG_ExceptSetBatteryLow              , 'Il valore deve essere compreso tra 5 e 90');
  SetResourceString(@MSG_ExceptOnAlterQrCodeStyle         , 'Non è possibile eseguire questa operazione dopo che il componente è stato inizializzato');
  SetResourceString(@MSG_ExceptConfigVersaoCompInvalida   , 'La tua versione del componente TWPPConnect non è compatibile con l'ultima versione di JavaScript, aggiorna la tua libreria su http://www.TWPPConnect.com.br/');
  SetResourceString(@MSG_ExceptUpdate                     , 'Errore del server WEB. Impossibile ricevere l'aggiornamento JS.ABR');
  SetResourceString(@MSG_WarningDuplicityDetected         , 'Invio dello stesso comando in un intervallo breve');
  SetResourceString(@MSG_ExceptJS_ABRUnknown              , 'Risposta sconosciuta da JS.ABR');
  SetResourceString(@MSG_ExceptNotAssignedOnGetQrCode     , 'OnGetQrCode non è stato definito');
  SetResourceString(@Text_FrmClose_Caption                , 'Attendere.. TWPPConnect si sta chiudendo..');
  SetResourceString(@Text_FrmClose_Label                  , 'Terminazione sicura di tutti i thread');
  SetResourceString(@Text_FrmClose_WarningClose           , 'Vuoi chiudere l\'applicazione?');
  SetResourceString(@Text_FrmQRCode_CaptionStart          , 'Caricamento QRCode...');
  SetResourceString(@Text_FrmQRCode_CaptionSucess         , 'Ora punta il tuo telefono!');
  SetResourceString(@Text_FrmQRCode_OnCLose               , 'Annullare la connessione al server di servizio?');
  SetResourceString(@MSG_ExceptPhoneNumberError           , 'Numero non valido');
  SetResourceString(@MSG_ExceptAlterDesigner              , 'Non è possibile modificare in modalità Designer');
  SetResourceString(@MSG_ExceptAlterInicialized           , 'Il metodo non può essere modificato dopo l'inizializzazione di TWPPConnect');
  SetResourceString(@MSG_ExceptCOntactNotFound            , 'Non ci sono contatti da esportare');
  SetResourceString(@MSG_ExceptCOntactSaveFile            , 'Impossibile salvare i contatti su %s');
  SetResourceString(@MSG_ExceptErrorLocateForm            , 'Errore nel localizzare il FORM');
  SetResourceString(@MSG_ExceptPath                       , 'Il percorso %s non è valido');
  SetResourceString(@MSG_ExceptGlobalCef                  , 'La classe GLOBALCEF non è stata definita in DPR');
  SetResourceString(@MSG_WarningClosing                   , 'Attendere... chiusura dell\'applicazione');
  SetResourceString(@MSG_WarningErrorFile                 , 'Errore sul file selezionato (%s)');
  SetResourceString(@MSG_ExceptMisc                       , 'Errore sconosciuto');
  SetResourceString(@Text_FrmConsole_Caption              , 'Componente TWPPConnect Brasile');
  SetResourceString(@Text_FrmConsole_LblMsg               , 'Attendere .. Inizializzazione di TWPPConnect');
  SetResourceString(@MSG_WarningClassUnknown              , 'Classe sconosciuta');
  SetResourceString(@MSG_Exceptlibeay32dll                , 'Il tuo computer non ha le DLL "libeay32.dll" e "ssleay32.dll". Per continuare, copia le DLL nella cartella di sistema o nella directory dell\'applicazione.');
  SetResourceString(@Text_Vcard_Comments1                 , 'Esportato dal componente TWPPConnect in: ');
  SetResourceString(@Text_Vcard_Comments2                 , 'Contatto silenziato');
  SetResourceString(@Text_Vcard_Comments3                 , 'Catturato in: ');
  SetResourceString(@MSG_WarningQrCodeStart1              , 'Una sessione precedente è ancora in corso, riprova più tardi');
  SetResourceString(@Text_Status_Serv_Initialized         , 'TWPPConnect connesso con successo al server di servizio');
  SetResourceString(@Text_Status_Serv_Initializing        , 'Inizializzazione di TWPPConnect al server di servizio');
  SetResourceString(@Text_Status_Serv_Disconnected        , 'Non connesso al server di servizio e TWPPConnect');
  SetResourceString(@Text_Status_Serv_Disconnecting       , 'Disconnesso dal server di servizio e TWPPConnect');
  SetResourceString(@Text_Status_Serv_Connected           , 'Connesso al server di servizio');
  SetResourceString(@Text_Status_Serv_ConnectedDown       , 'Sessione terminata tramite cellulare');
  SetResourceString(@Text_Status_Serv_Connecting          , 'Attendere, connessione al server di servizio');
  SetResourceString(@Text_Status_Serv_ConnectingNoPhone   , 'Errore di connessione, telefono spento');
  SetResourceString(@Text_Status_Serv_ConnectingReaderQR  , 'In attesa della scansione del codice QR');
  SetResourceString(@Text_Status_Serv_TimeOut             , 'Impossibile connettersi (Timeout)');
  SetResourceString(@Text_Status_Serv_Destroying          , 'Distruggendo e chiudendo TWPPConnect');
  SetResourceString(@Text_Status_Serv_Destroy             , 'TWPPConnect è stato terminato');
  SetResourceString(@MSG_WarningNothingtoSend             , 'Non c\'è contenuto da inviare in questo messaggio');
  SetResourceString(@MSG_Except_Data_TypeObj              , 'Il tipo di oggetto non è compatibile');
  SetResourceString(@MSG_Except_DATA_ConnectRepass        , 'Il tipo di DataSet non ha una connessione al database');
  SetResourceString(@MSG_Except_DATA_ConnectionNull       , 'Connessione non collegata');
  SetResourceString(@MSG_Except_AtribuicaoInvalida        , 'Attribuzione non valida (già in uso da un altro oggetto)');
  
  SetResourceString(@MSG_WarningDeveloper                 , 'Avviso per lo sviluppatore (IDE)');
  SetResourceString(@Text_DefaultPathDown                 , 'TWPPConnectAttachment');
  SetResourceString(@Text_DefaultError                    , 'Errore nella creazione della directory in ');
  SetResourceString(@MSG_Except_SaveAttached              , 'Errore nel salvataggio del file allegato al messaggio');
  SetResourceString(@MSG_Except_CefNull                   , 'Il componente GlobalCEFApp non è stato inizializzato nell\'applicazione (Controlla DPR dell\'app DEMO)');
  SetResourceString(@Text_System_memUse                   , 'Memoria totale utilizzata da questa applicazione: ');
  SetResourceString(@Text_System_memTot                   , 'Memoria totale di sistema: ');
  SetResourceString(@Text_System_memFree                  , 'Memoria fisica disponibile: ');
  SetResourceString(@Text_System_memLoad                  , 'Carico di memoria: ');
  SetResourceString(@Text_FrmConfigNetWork_Caption        , 'Configurazione LAN');
  SetResourceString(@Text_FrmConfigNetWork_ProxyTypeLbl   , 'Tipo:');
  SetResourceString(@Text_FrmConfigNetWork_ProxyServerLbl , 'Server:');
  SetResourceString(@Text_FrmConfigNetWork_PrtocolLbl     , 'Protocollo:');
  SetResourceString(@Text_FrmConfigNetWork_ProxyPortLbl   , 'Porta:');
  SetResourceString(@Text_FrmConfigNetWork_ProxyUsernameLbl           , 'Nome utente:');
  SetResourceString(@Text_FrmConfigNetWork_ProxyPasswordLbl           , 'Password:');
  SetResourceString(@Text_FrmConfigNetWork_ProxyScriptURLLbl          , 'Script di configurazione automatica:');
  SetResourceString(@Text_FrmConfigNetWork_ProxyByPassListLbl         , 'Non usare proxy per gli indirizzi: (usa i punti e virgola per separare le voci)');
  SetResourceString(@Text_FrmConfigNetWork_MaxConnectionsPerProxyLbl  , 'Connessioni massime per proxy:');
  SetResourceString(@Text_FrmConfigNetWork_GroupBox2                  , ' Intestazione personalizzata: ');
  SetResourceString(@Text_FrmConfigNetWork_HeaderNameLbl              , 'Nome "Variabile":');
  SetResourceString(@Text_FrmConfigNetWork_HeaderValueLbl             , 'Valore "Variabile":');
  SetResourceString(@Text_FrmConfigNetWork_BntOK                      , 'Salva');
  SetResourceString(@Text_FrmConfigNetWork_BntCancel                  , 'Rinuncia');
  SetResourceString(@Text_FrmConfigNetWork_QuestionSave               , 'Conferma l''aggiornamento di questi dati ?');

end;

**Comment by marcelo386** [comment]
added your suggestion to the code, I took advantage and added other languages
