### ISSUE TITLE
Legenda opcional não fica vazia ao enviar arquivo sem a 'caption' definida nas opções

### ISSUE THREAD

**Issue by Nullzd** [wppconnect-team/WPP4Delphi#95]
Ao não adicionar 'caption' ou informa-la como vazia (ex.: 'caption: "" ') a função SendFileMessageEx utiliza o nome do arquivo(filename) definida nas opções como legenda para o arquivo a ser enviado. Existe algum metodo para enviar sem a legenda preenchida?

**Comment by marcelo386** [comment]
Isso é padrão do WhatsApp, se não passar o caption ele assume o nome do arquivo

**Comment by Nullzd** [comment]
![image](https://github.com/user-attachments/assets/8bb94b9d-d8a8-4b02-8467-bfc525adfc80)
Entao apesar da legenda ser opcional no Whatsapp web, pelo WPP4Delphi sempre irá preenchido?
Como pode ser visto na imagem anexada onde o primeiro arquivo foi enviado pelo WPP4Delphi enquanto que o segundo foi diretamente pelo Whatsapp web

**Comment by marcelo386** [comment]
É próprio whatsapp que faz isso, na exibição de arquivos, enviado ou não pelo componente, sempre irá ter este comportamento

**Comment by Nullzd** [comment]
Ok, obrigado
